# Vizualizing BigQuery data in a Jupyter notebook

[BigQuery](https://cloud.google.com/bigquery/docs/) is a petabyte-scale analytics data warehouse that you can use to run SQL queries over vast amounts of data in near realtime.

[Google Datasets](https://console.cloud.google.com/marketplace/browse?filter=solution-type:dataset) as of December 11, contains 207 ranging from income by Country, numerous Covid collections, climate, and global health view from The World Bank

Data visualization tools can help you make sense of your BigQuery data and help you analyze the data interactively. You can use visualization tools to help you identify trends, respond to them, and make predictions using your data. In this tutorial, you use the BigQuery Python client library and pandas in a Jupyter notebook to visualize data in the BigQuery natality sample table.

In [ ]:
from google.cloud import bigquery
import pandas

In [1]:
%%bigquery
select * from `bigquery-public-data.covid19_nyt.us_counties`
order by date DESC, confirmed_cases DESC
limit 20

,date,county,state_name,county_fips_code,confirmed_cases,deaths
0,2020-12-13,Los Angeles,California,06037,525651,8298
1,2020-12-13,New York City,New York,None,360700,24501
2,2020-12-13,Cook,Illinois,17031,352409,7340
3,2020-12-13,Miami-Dade,Florida,12086,257856,3981
4,2020-12-13,Maricopa,Arizona,04013,253686,4353
5,2020-12-13,Harris,Texas,48201,207406,3150
6,2020-12-13,Dallas,Texas,48113,157336,1728
7,2020-12-13,Clark,Nevada,32003,141231,1999
8,2020-12-13,San Bernardino,California,06071,126738,1223
9,2020-12-13,Broward,Florida,12011,120166,1741
10,2020-12-13,Tarrant,Texas,48439,119630,1180
11,2020-12-13,Riverside,California,06065,118335,1573
12,2020-12-13,San Diego,California,06073,107435,1162
13,2020-12-13,Orange,California,06059,104817,1694
14,2020-12-13,Bexar,Texas,48029,94194,1577
15,2020-12-13,Salt Lake,Utah,49035,93761,473
16,2020-12-13,El Paso,Texas,48141,92810,1374
17,2020-12-13,Milwaukee,Wisconsin,55079,82954,829
18,2020-12-13,Philadelphia,Pennsylvania,42101,79646,2206
19,2020-12-13,Hennepin,Minnesota,27053,79134,1243

# Trinette's Wish List

[GDELT 2.0 Event Database](https://console.cloud.google.com/marketplace/product/the-gdelt-project/gdelt-2-events)  is a global catalog of worldwide activities (“events”) in over 300 categories from protests and military attacks to peace appeals and diplomatic exchanges. Each event record details 58 fields capturing many different attributes of the event. The GDELT 2.0 Event Database currently runs from February 2015 to present, updated every 15 minutes and is comprised of 326 million mentions of 103 million distinct events as of February 19, 2016. This dataset uses machine translation coverage of all monitored content in 65 core languages, with a sample of an additional 35 languages hand translated.
AND 3.0 is Coming Soon!

[Google BigQuery + GDELT](https://www.gdeltproject.org/data.html#googlebigquery) all GDELT datasets are available in Google BigQuery, with live datasets updated every 15 minutes.

[GDELT demos](https://blog.gdeltproject.org/a-compilation-of-gdelt-bigquery-demos/) Get lost in the demos - many are very dated ... but just look at the things you can do - the questions you can think of with all this translated data. 
???What ethics are being applied to all this public information collected around the world --- every 15 minutes. ????

[simple network visualizations](http://blog.gdeltproject.org/getting-started-with-gdelt-google-cloud-datalab-simple-network-visualizations/) Jupyter notebook -- the syntax is dated especially if you use Google JupyterLab to interface with BigQuery. 

[Research Checklists](https://dimewiki.worldbank.org/wiki/Check_Lists) Do you remember every step of the validation and verification process when preparing data or the timing and flow of questions? These quick reference checklists help with ticking off the boxes before finalizing a visualization or submitting your table to the research team.